### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by VladimirWebDev** [Way2CU/Ronen-3D-Sound-Site#1]
![image](https://user-images.githubusercontent.com/25882157/28835185-d5fca156-76e4-11e7-8aea-e0c9d03d3017.png)
Missing image, in export, for adaptor for both desktop and mobile versions.

**Comment by talovdat** [comment]
Image in export.

_Sent from my Samsung SM-J710F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
